[package]
name = "eschanostr"
version = "1.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
ctrlc = { version = "3.4.5", features = ["termination"] }
nostr = "0.35.0"
regex = "1.11.1"
