services:
  neschalotstr-dev:
    image: neschalotstr-dev
    container_name: neschalotstr-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /neschalotstr
    volumes:
      - ..:/neschalotstr:cached
    tty: true
