services:
  eschanostr-dev:
    image: eschanostr-dev
    container_name: eschanostr-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /eschanostr
    volumes:
      - ..:/eschanostr:cached
    tty: true
